import { Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/global/Navbar'; // Adjust the path if needed
import Footer from '@/components/global/Footer'; // Adjust the path if needed

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body className="antialiased">
        <Navbar />
        <main className="pt-16">{children}</main> <Footer />
        {/* Push content below navbar */}
      </body>
    </html>
  );
}
